name: Deploy Blockscout on AWS

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version to deploy (e.g., v1.0.0)"
        required: true
      rpc_url:
        description: "RPC URL of the Substrate node"
        required: true

jobs:
  deploy-blockscout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject RPC URL into setup script
      run: |
        echo '#!/bin/bash' > scripts/setup_with_rpc.sh
        echo 'set -e' >> scripts/setup_with_rpc.sh
        echo 'export DEBIAN_FRONTEND=noninteractive' >> scripts/setup_with_rpc.sh
        # Properly escape the RPC URL
        ESCAPED_RPC_URL=$(echo "${{ inputs.rpc_url }}" | sed 's/[\/&]/\\&/g')
        echo "RPC_URL=\"$ESCAPED_RPC_URL\"" >> scripts/setup_with_rpc.sh
        cat scripts/setup.sh >> scripts/setup_with_rpc.sh  # Append actual setup script
    
    - name: Create AWS EC2 instance for Blockscout
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        INSTANCE_ID=$(aws ec2 run-instances --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"VolumeSize":40,"VolumeType":"gp3"}}]' \
          --image-id ami-04b4f1a9cf54c11d0 --count 1 --instance-type t3.large --security-group-ids sg-0442d41440d018db1 \
          --key-name unforkable \
          --user-data file://scripts/setup_with_rpc.sh \
          --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=blockscout-${{ inputs.release_version }}},{Key=Project,Value=Blockscout}]" \
          --query "Instances[0].InstanceId" --output text)
        
        echo "BLOCKSCOUT_INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
        echo "New AWS EC2 instance created with ID: $INSTANCE_ID"

    - name: Get Public IP of the Instance
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "Waiting for instance to be ready..."
        aws ec2 wait instance-status-ok --instance-ids $BLOCKSCOUT_INSTANCE_ID
        
        echo "Waiting for public IP to be assigned..."
        MAX_RETRIES=10
        RETRY_COUNT=0
        PUBLIC_IP=""
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $BLOCKSCOUT_INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          if [ -n "$PUBLIC_IP" ] && [ "$PUBLIC_IP" != "None" ]; then
            echo "✅ Public IP detected: $PUBLIC_IP"
            break
          fi
          echo "⚠️ Attempt $((RETRY_COUNT + 1))/$MAX_RETRIES: Waiting for public IP..."
          RETRY_COUNT=$((RETRY_COUNT + 1))
          sleep 10
        done
        
        if [ -z "$PUBLIC_IP" ] || [ "$PUBLIC_IP" = "None" ]; then
          echo "❌ ERROR: Could not get public IP after $MAX_RETRIES attempts!"
          exit 1
        fi
        
        echo "BLOCKSCOUT_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
        echo "AWS Instance Public IP: $PUBLIC_IP"

    - name: Wait for Instance to Be Ready and Services to Start
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "Waiting for AWS instance to be ready..."
        aws ec2 wait instance-status-ok --instance-ids $BLOCKSCOUT_INSTANCE_ID
        echo "AWS instance is now running."
        
        # Wait additional time for services to start
        echo "Waiting for services to start..."
        sleep 300
               
    - name: Output Blockscout URL
      run: |
        echo "Blockscout is now deployed at: http://$BLOCKSCOUT_PUBLIC_IP"
        echo "Note: It may take a few minutes for all services to fully initialize."
